### ISSUE TITLE
I18n support für Metadaten und Talks

### ISSUE THREAD

**Issue by sippsack** [dukecon/dukecon#12]
Sprache wird über Accept-Language Header ausgwählt.

Metadaten: 

Tracks
Sprachen
Levels (Audience)

Jetzt nicht, ggf. später: Keywords, Vortragstyp

Talks:
liefern für Track, Language und Level entsprechend Codes (track1, ...) aus, die die Clients über die Meta-Daten ersetzen müssen.

**Comment by sippsack** [comment]
Metadaten können jetzt abgerufen werden über REST-Service. Wo es Sinn macht, werden deutsche und englische Begriffe geschickt.

http://dev.dukecon.org/latest/rest/meta

{
  "conference": {
    "id": 499959,
    "name": "Javaland 2016",
    "url": "http://dev.dukecon.org/latest/"
  },
  "rooms": [
    {
      "order": 1,
      "name": "Wintergarten"
    },
    {
      "order": 2,
      "name": "Schauspielhaus"
    },
    {
      "order": 3,
      "name": "Quantum 1+2"
    },
    {
      "order": 4,
      "name": "Quantum 3"
    },
    {
      "order": 5,
      "name": "Quantum 4"
    },
    {
      "order": 6,
      "name": "Lilaque"
    },
    {
      "order": 7,
      "name": "Neptun"
    }
  ],
  "languages": [
    {
      "code": "de",
      "name": "Deutsch"
    },
    {
      "code": "en",
      "name": "English"
    }
  ],
  "defaultLanguage": {
    "code": "de",
    "name": "Deutsch"
  },
  "tracks": [
    {
      "order": 1,
      "names": {
        "de": "Container & Microservices",
        "en": "container & microservices"
      }
    },
    {
      "order": 2,
      "names": {
        "de": "Core Java & JVM basierte Sprachen",
        "en": "Core Java & JVM based languages"
      }
    },
    {
      "order": 3,
      "names": {
        "de": "Enterprise Java & Cloud",
        "en": "enterprise Java & cloud"
      }
    },
    {
      "order": 4,
      "names": {
        "de": "Frontend & Mobile",
        "en": "frontend & mobile"
      }
    },
    {
      "order": 5,
      "names": {
        "de": "IDEs & Tools",
        "en": "IDEs & tools"
      }
    },
    {
      "order": 6,
      "names": {
        "de": "Internet der Dinge",
        "en": "internet of things"
      }
    },
    {
      "order": 7,
      "names": {
        "de": "Architektur & Sicherheit",
        "en": "architecture & security"
      }
    },
    {
      "order": 8,
      "names": {
        "de": "Newcomer",
        "en": "newcomer"
      }
    }
  ],
  "audiences": [
    {
      "order": 1,
      "names": {
        "de": "Anfänger",
        "en": "beginners"
      }
    },
    {
      "order": 2,
      "names": {
        "de": "Fortgeschrittene",
        "en": "advanced"
      }
    }
  ],
  "talkTypes": [
    {
      "order": 1,
      "names": {
        "de": "Best Practices",
        "en": "best practices"
      }
    },
    {
      "order": 2,
      "names": {
        "de": "Keynote",
        "en": "keynote"
      }
    },
    {
      "order": 3,
      "names": {
        "de": "Neuerscheinungen oder Features",
        "en": "new releases or features "
      }
    },
    {
      "order": 4,
      "names": {
        "de": "Projektbericht",
        "en": "project report"
      }
    },
    {
      "order": 5,
      "names": {
        "de": "Tipps & Tricks",
        "en": "tips & tricks"
      }
    }
  ]
}

**Comment by sippsack** [comment]
Den talks Rest-Service gibt es jetzt in einer v2, der noch die internen IDs aus den Metadaten enthält. Wenn alle Clients umgestellt haben, können wir das v2 auch wieder weglassen, außerdem sollte der Service die hardcodierten Namen dann auch noch entfernen.

[
  {
    "id": "509464",
    "track": "Enterprise Java & Cloud",
    "trackNumber": 3,
    "level": "Anfänger",
    "levelNumber": 1,
    "type": "Best Practices",
    "typeNumber": 1,
    "start": "2016-03-09T09:00",
    "end": "2016-03-09T09:40",
    "location": "Quantum 1+2",
    "roomNumber": 3,

**Comment by ascheman** [comment]
@sippsack still relevant for 1.1? Please close or postpone ...
