### ISSUE TITLE
Offline mode not always working

### ISSUE THREAD

**Issue by JOpsDev** [dukecon/dukecon#17]
Depending on the device and the browser the offline mode is sometimes not working.
For example the default browser on a HTC One Mini displays a warning once and does not work afterwards.
Also Firefox 40.0.3 on Fedora Linux either tries to load forever if you click on the details page or it shows a details page without any content filled in.

HTC One Mini:

First click after enabling "flight mode":
![screenshot_2015-09-25-10-02-42](https://cloud.githubusercontent.com/assets/6024472/10096335/fbd8278a-6370-11e5-96b6-b59078ae7def.png)

What is displayed after that:
![screenshot_2015-09-25-10-02-59](https://cloud.githubusercontent.com/assets/6024472/10096343/04062c4a-6371-11e5-9c61-0537e8afdbe9.png)

Clicking on "Talks" again:
![screenshot_2015-09-25-10-03-13](https://cloud.githubusercontent.com/assets/6024472/10096345/0744215a-6371-11e5-9506-30de01546ba7.png)

If the network connection is back the next click will make everything work properly again.

**Comment by ascheman** [comment]
@JOpsDev thanks for the report! For the HTC device: Could you please tell us which browser version it has and if any alternative browser is available there which is able to run in offline mode with DukeCon? Which one?

I fear both devices are currently to exotic to further investigate this, but we will maybe even list a number of devices where problems where reported.

**Comment by ascheman** [comment]
This issue was moved to dukecon/dukecon_html5#7
