### ISSUE TITLE
localStorage-Fehler bei Metadaten-Änderungen

### ISSUE THREAD

**Issue by ascheman** [dukecon/dukecon#2]
Gelegentlich bleiben Daten im localStorage stehen, wenn sich HTML-Inhalte oder Vortragsdaten ändern. Das führt z.B. zu einer leeren Anzeige der Vorträge, wenn sich ein Track-Schlüssel geändert hat.

Beispiel:
Im localStorage steht folgendes (Track-Titel von 2015 als Filter gesetzt):

```
Storage { 
    dukeconfilters_track: "["Cloud and Big Data"]", 
    dukeconfilters_location: "[]", 
    dukeconfilters_level: "[]", 
    dukeconfilters_language: "[]", 
    length: 4 
}
```

Wird die Seite nun mit Daten von 2016 neu geladen, so gibt es neue Track-Titel von 2016, aber der Filter bleibt aktiv und es werden _gar keine_ Talks angezeigt. Das kann auch jederzeit passieren, wenn sich z.B. Track-Titel ändern.

**Comment by annam002** [comment]
Fixed
