### ISSUE TITLE
Events longer than one hour should appear in every one hour slot

### ISSUE THREAD

**Issue by sippsack** [dukecon/dukecon#27]
Community events or workshops (e.g. JavaInnovationLab) appear at 9 o'clock with a length of 480 minutes. When attendees look for an event in the afternoon, they won't recognize it.

Further possible solution: separate track for all events longer than one hour which spans the whole day instead of hourly seperation.

**Comment by ascheman** [comment]
This issue was moved to dukecon/dukecon_pwa#56
