### ISSUE TITLE
Footer auf der Talkseite nicht am Seitenende

### ISSUE THREAD

**Issue by annam002** [dukecon/dukecon#3]
Der Footer auf der Talkseite ist nicht wirklich am Seitenende. Abhängig davon, welche Größe das Browserfenster hat, ist er zu hoch oder man muss runterscrollen um ihn zu sehen. Könnte verbessert werden.

**Comment by steffchep** [comment]
Fixed! 

Habe den Footer so angepasst, dass man dort jetzt auch Unter Umständen eine Daumen-Navigation unterbringen könnte (so wie im Flex-Client) - er bleibt zumindest auf Android in Chrome und Firefox schön im Bild. Kann das jemand auf einem iPain noch testen?
