### ISSUE TITLE
Warn participants about long walking distances between selected talks

### ISSUE THREAD

**Issue by JOpsDev** [dukecon/dukecon#30]
As the conferences grow we will have longer walking distances between the lecture rooms. There may even be 10-15 minute walks in very bad cases. 
Since the pauses between talks is not much longer participants should be warned if they selected talks that need you to start walking towards the next lecture room right after the previous talk ended.

We need to have the proper room ID for each talk. Also we need the walking time between two rooms for each room combination or a model to calculate the time.
If then combined with the personal selections of a participant warnings could be displayed where appropriate.

**Comment by ascheman** [comment]
This issue was moved to dukecon/dukecon_pwa#55

**Comment by ascheman** [comment]
This issue is only about the visualization in the front end. Please request additional information from the dukecon_server project by separate ticket.
