### ISSUE TITLE
Allow for external imprints

### ISSUE THREAD

**Issue by ascheman** [dukecon/dukecon#33]
Some DukeCon-Conferences, e.g., Javaland will have a home page which contains already an imprint. Enable DukeCon to set a link to this imprint instead of incorporating the data internally.
* In dukecon/dukecon_server add configuration/deliver link location to frontend (@sippsack?)
* In dukecon/dukecon_html5 (@steffchep) + dukecon/dukecon_flex (@chrisdutz): eval. link configuration and provide link

**Comment by ascheman** [comment]
Do we need to distinguish by language?

**Comment by sippsack** [comment]
if we have different languages, we could deliver multiple imprint links:

imprint.link.de = http://
imprint.link.en = http://

otherwise we could also link to only one of the imprint pages, and the users have to use the language switch on the conference page.

**Comment by ascheman** [comment]
Already implemented
