### ISSUE TITLE
Add a little Infobox or icon if favorited multiple talks in the same time slot

### ISSUE THREAD

**Issue by noctarius** [dukecon/dukecon#35]
When favoriting talks from the timetable, the slots are obvious but when looking through topic areas I might have a chance to select multiple talks which happen in parallel. Maybe a small infobox would be nice or adding a little yellow exclamation mark to the header and show the info if the user hovers or clicks it :)

**Comment by ascheman** [comment]
This issue was moved to dukecon/dukecon_pwa#54
