### ISSUE TITLE
Allow more word variants in search

### ISSUE THREAD

**Issue by dasniko** [dukecon/dukecon#36]
Currently, the _"Code Golf"_ activities can only be found when the term `code-golf` is entered exactly like it is represented in the data (or fragments like `code` or `golf`).
It would be nice to find the activities also when entering `codegolf` or `code golf`.

This would be a benefit not only for the Code Golf activity, but also for all other talks/activities which deal with word variants and/or composite words.

**Comment by ascheman** [comment]
This issue was moved to dukecon/dukecon_pwa#53
