### ISSUE TITLE
reduce size of speaker images

### ISSUE THREAD

**Issue by JOpsDev** [dukecon/dukecon#39]
can the image size be reduced through some measures? I might be enough to enforce the *JPG* format.

Example:

https://programm.javaland.eu/2017/rest/speaker/images/ea7f7b5ce9f6cfdf088e093ad8a6e531
is a 400x400 PNG image with ca. 400KB in size. It is displayed as a 158x158 icon on the talk's detail page.
As a 400x400 *JPG* image the size is reduced to 18KB. Most other 400x400 JPGs pages are 40KB in size.

**Comment by ascheman** [comment]
This issue was moved to dukecon/dukecon_server#76
