### ISSUE TITLE
Strange characters in talk details

### ISSUE THREAD

**Issue by annam002** [dukecon/dukecon#46]
In the talk 100% Code Coverage strange characters are shown instead of dashes. Using the Brave Browser on Android.

**Comment by annam002** [comment]
![screenshot_20180312-171120](https://user-images.githubusercontent.com/3940199/37295747-3c96f87e-2619-11e8-9ce0-10de55c424f9.png)

**Comment by ascheman** [comment]
This issue was moved to dukecon/dukecon_pwa#50
