### ISSUE TITLE
Clarify usage of "Aktiv"-checkbox

### ISSUE THREAD

**Issue by michael-simons** [dukecon/dukecon#48]
The highlighted checkbox in this image

![img_b5ee999a02a6-1](https://user-images.githubusercontent.com/526383/37457249-b4c3e2a6-2841-11e8-90d8-a083a6597049.jpeg)

is irritating. It looks like it is part of the available filter options (like all talks "active") but in fact toggles the configured filtered. As such it should be on the same level as the "Zurücksetzen" button and behave like a toggle button (that is a button that stays in the "pressed" or "active" state).

**Comment by ascheman** [comment]
This issue was moved to dukecon/dukecon_pwa#49
