### ISSUE TITLE
"Aktiv" checkbox in favorites doesn't remember its state

### ISSUE THREAD

**Issue by michael-simons** [dukecon/dukecon#49]
I'm on iOS.

Scenario:
* Create a set of filters
* Activate the set with the active checkbox 
* Be happy about filtered list
* Untick active checkbox
* Be happy about unfiltered list
* Hit reload or open a new tab
* Active checkbox is ticked again

Expected:
* Active checkbox stays unticked.

**Comment by ascheman** [comment]
This issue was moved to dukecon/dukecon_pwa#47
