### ISSUE TITLE
Caching von "rest/talks" ersetzen!

### ISSUE THREAD

**Issue by ascheman** [dukecon/dukecon#5]
Wenn "rest/talks" im Cache Manifest steht, holt der Client niemals aktualisierte Daten (s. JS Console/Netzaktivitäten). Hatte versucht, das zu beheben (vgl. [dukecon_html5/commit/684cd72d](https://github.com/dukecon/dukecon_html5/commit/684cd72d2314af0ef68d1fa8cee26a89ac0b3ef7)). Aber leider führt das dazu, dass der Client nicht mehr Offline-fähig ist. Da muss also vermutlich noch mehr gemacht werden.

**Comment by annam002** [comment]
Fixed. The problem was that we did not store the data in the db... :o
