### ISSUE TITLE
Fix "zurück" button

### ISSUE THREAD

**Issue by michael-simons** [dukecon/dukecon#50]
The "Zurück"-Button should work in a consistent way.

When the user has tapped on a talk like in

![img_8b79fee5c1c9-1](https://user-images.githubusercontent.com/526383/37458027-f088d45c-2843-11e8-9b10-bde6c39b8ff4.jpeg)

It navigates back into the talk list

![img_6ac66b5c2cbf-1](https://user-images.githubusercontent.com/526383/37458065-10550b20-2844-11e8-8e07-81c133705f3f.jpeg)

That's fine.

If the user navigates between the days, the user expect that the back button moves back to the previous day. Instead it navigates out of the app back into the homepage or whatever.

**Comment by ascheman** [comment]
This issue was moved to dukecon/dukecon_pwa#46
