### ISSUE TITLE
Fix navigation out of the filter list

### ISSUE THREAD

**Issue by michael-simons** [dukecon/dukecon#51]
The only way to close the filter list on iOS is the highlighted, small button:

![img_b5ee999a02a6-1](https://user-images.githubusercontent.com/526383/37458135-58b073dc-2844-11e8-91c6-7ff53c0e4f27.jpeg)

As a user I'd expect that I can hit somewhere outside the filter panel to close it on iOS.

**Comment by ascheman** [comment]
This issue was moved to dukecon/dukecon_pwa#48
