### ISSUE TITLE
[PANIC] Aufruf der JavaLand-Programmseite 2020-01-24 12:31

### ISSUE THREAD

**Issue by mkarg** [dukecon/dukecon#59]
![image](https://user-images.githubusercontent.com/1701815/73066208-ad863080-3ea5-11ea-97a2-15ef97874eec.png)

**Comment by ascheman** [comment]
Thanks for the issue, @mkarg - could you please try again.
I am not running into problems like this currently.

**Comment by mkarg** [comment]
@ascheman Gerd, thanks for fixing this. Tried again and LGTM now. :+1:

**Comment by ascheman** [comment]
You are welcome @mkarg 
To be honest, I did nothing: The DukeCon Web application has to download the conference data at least once. Then it is able to show it offline and tries to get new data/versions in the background (and of course update the conference program to the user).
For some reason you had bad luck, e.g.,
* The fronend/application could be loaded but downloading of the data failed (broken connection),
* The data backend was down in this very moment (it is not h/a)?

We will never know. The frontend should be so fault tolerant that it would eventually load the data later and show it as soon as it could complete the request to the backend.
Anyways: Thanks for the hint!

**Comment by mkarg** [comment]
In this case maybe it would be a good idea if the UI says "Loading Data..." instead of "This conference does not *exist*". ;-)
