### ISSUE TITLE
Regelmäßiges Pullen von neuen Daten

### ISSUE THREAD

**Issue by annam002** [dukecon/dukecon#7]
Im Moment werden die Daten immer erst vom Server geholt, und wenn der Server nicht verfügbar ist, aus dem lokalen Speicher. Das kann unter Umständen langsam sein, weil immer auf die Antwort vom Server gewartet wird.
Idee: Die Daten einmal holen und lokal speichern. Beim Aufruf der Seite die Daten immer aus dem lokalen Speicher holen. Im Hintergrund regelmäßig die lokalen Daten mit dem Neuesten vom Server auffrischen.

**Comment by ascheman** [comment]
This issue was moved to dukecon/dukecon_html5#11
